<?php

/**
 * @file
 * Contains svg_linking.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function svg_linking_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the svg_linking module.
    case 'help.page.svg_linking':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds support for linking internal and external svgs') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function svg_linking_theme() {
  $theme = [];

  return $theme;
}
